AutoTransfer:
  - name: Ключ1
    keyType: key
    keyValue: 47944e274f58e5984b8be6a1139534dcfdedec668c44aa1dad03070ec020daea
    recipient: BHZJ3obt9IYWJWO8r1wQwhpmGpMHjgru1QhZRNq50o30K0FuDF3DaAeI8Wc9fChkjLyFbtH8ajdeLjZiVwEH3rU=
    interval: 3
  - name: Ключ2
    keyType: seed
    keyValue: muffin,elbow,monster,regular,burger,lady,thrive,virtual,curve,mammal,reflect,venue
    recipient: BHZJ3obt9IYWJWO8r1wQwhpmGpMHjgru1QhZRNq50o30K0FuDF3DaAeI8Wc9fChkjLyFbtH8ajdeLjZiVwEH3rU=
    interval: 5
  - name: Ууууууу
    keyType: key
    keyValue: CAISIH62lIdicSwIof8Hnc34lI5+n8mETKn2Gedw7R/dg+zy
    recipient: BHZJ3obt9IYWJWO8r1wQwhpmGpMHjgru1QhZRNq50o30K0FuDF3DaAeI8Wc9fChkjLyFbtH8ajdeLjZiVwEH3rU=
    interval: 10