# Наша группа https://t.me/btt_manager
# YAML за 5 минут: синтаксис и основные возможности https://tproger.ru/translations/yaml-za-5-minut-sintaksis-i-osnovnye-vozmozhnosti/

# Настройки автоматического перевода
AutoTransferWallets:
    # Имя кошелка, для вывода в логи. Придумываем сами
  - name: NameKey1
    # Тип ключа, который будете указывать в keyValue, возможные варианты: key, seed
    keyType: key
    # Ключ или 12 слов в зависимости от указанного keyType
    # 12 слов указываем с маленькой буквы через запятую
    # Ключ можно использовать из speed или btfs
    keyValue: 47944e274f58e5984b8be6a1139534dcfdedec668c44aa1dad03070ec020daea
    # Получатель переводов, его можно получить:
    # 1. В кошельке speed, указав порт http://127.0.0.1:ВАШ_ПОРТ_SPEED/api/public_key
    # 2. Через программу address2.exe https://github.com/aliasxrus/get-tron-address
    recipient: BHZJ3obt9IYWJWO8r1wQwhpmGpMHjgru1QhZRNq50o30K0FuDF3DaAeI8Wc9fChkjLyFbtH8ajdeLjZiVwEH3rU=
    # Пауза между переводами в секундах
    interval: 3

    # Взять ключ из SPEED:
#  - name: SpeedKey
#    keyType: speed
#    recipient: BHZJ3obt9IYWJWO8r1wQwhpmGpMHjgru1QhZRNq50o30K0FuDF3DaAeI8Wc9fChkjLyFbtH8ajdeLjZiVwEH3rU=
#    interval: 3
#    portFile: C:\Users\Administrator\AppData\Local\BitTorrentHelper\port
#    speedPassword: BHZJ3obt9IYWJWO8r1wQ

    # Одновременно можно указать много кошельков:
#  - name: NameSeed2
#    keyType: seed
#    keyValue: muffin,elbow,monster,regular,burger,lady,thrive,virtual,curve,mammal,reflect,venue
#    recipient: BHZJ3obt9IYWJWO8r1wQwhpmGpMHjgru1QhZRNq50o30K0FuDF3DaAeI8Wc9fChkjLyFbtH8ajdeLjZiVwEH3rU=
#    interval: 5
#  - name: NameKey3
#    keyType: key
#    keyValue: CAISIH62lIdicSwIof8Hnc34lI5+n8mETKn2Gedw7R/dg+zy
#    recipient: BHZJ3obt9IYWJWO8r1wQwhpmGpMHjgru1QhZRNq50o30K0FuDF3DaAeI8Wc9fChkjLyFbtH8ajdeLjZiVwEH3rU=
#    interval: 10

# Настройки автоматического вывода
AutoWithdrawConfig:
  # Пауза между получением баланса шлюза, в миллисекундах. Интервал менее 1000 опасен, возможна пожизненная блокировка.
  interval: 1000
  # Ссылка для получения баланса. Поддерживает TronGrid и TronScan
  url: "https://api.trongrid.io/v1/accounts/41c109c53d081d1baf2aa792c7eef5b3a76df4f711"
#  url: "https://apilist.tronscan.org/api/account?address=TTZu7wpHa9tnQjFUDrsjgPfXE7fck7yYs5"
  # ** ОПЦИОНАЛЬНО ** Api key для TronGrid
  apiKey: ""
  # Частота обновления баланса кошельков, в секундах
  refreshTimeout: 60
  # Минимальный таймаут между попытками вывода, в миллисекундах
  timeoutWithdraw: 0

# Кошельки для автоматического вывода
AutoWithdrawWallets:
    # Имя кошелка, для вывода в логи. Придумываем сами
  - name: NameKey4
    # Тип ключа, который будете указывать в keyValue, возможные варианты: key, seed
    keyType: key
    # Ключ или 12 слов в зависимости от указанного keyType
    # 12 слов указываем с маленькой буквы через запятую
    # Ключ можно использовать из speed или btfs
    keyValue: 47944e274f58e5984b8be6a1139534dcfdedec668c44aa1dad03070ec020daea
    # Выводить только когда есть другие выводы из шлюза. Минимальная разница в балансе шлюза между запросами получения баланса для попытки вывода.
    difference: 0
    # Минимальный баланс BTT на шлюзе при котором начинать попытку вывода.
    minAmount: 0
    # Максимальный баланс BTT на шлюзе, 0 - отключено.
    maxAmount: 0
    # Минимальный таймаут между попытками вывода для этого кошелька, в миллисекундах
    timeoutWalletWithdraw: 0
    # ** ОПЦИОНАЛЬНО ** Получатель платежа, позволяет выводить на другой кошелёк.
    # Узнать адрес можно заменив конец этой ссылки на свой адрес https://api.trongrid.io/v1/accounts/TR5vQjeg6LojfCKyvafhENMeAbJLTLQYh4 , нужное нам поле (их несколько, не перепутайте) "address":"41a5cef2c8aa4b4a5381a6889019e85080ef95c290", то что в этом поле и буде вашим адресом получателя
    # Можно проверить правильность ввода заменив конец этой ссылки https://api.trongrid.io/v1/accounts/41a5cef2c8aa4b4a5381a6889019e85080ef95c290 и перейдя по ней
    # Все эти адреса программа выводит в консоль при запуске. Для использования необходимо раскомментировать нижнюю строчку (удалить # в начале строки)
#    bttRecipientAddress: 41a5cef2c8aa4b4a5381a6889019e85080ef95c290

  # Одновременно можно указать много кошельков:
#  - name: NameSeed5
#    keyType: seed
#    keyValue: muffin,elbow,monster,regular,burger,lady,thrive,virtual,curve,mammal,reflect,venue
#    difference: 1
#    minAmount: 20000
#    bttRecipientAddress:
#  - name: NameSeed6
#    keyType: seed
#    keyValue: muffin,elbow,monster,regular,burger,lady,thrive,virtual,curve,mammal,reflect,venue
#    difference: 1
#    minAmount: 20000
#    bttRecipientAddress:

IpFilterConfig:
  # Частота блокировок
  interval: 3
  # Максимальное количество заблокированных IP
  length: 5000
  # Путь до ipfilter.dat
  path: ./ipfilter.dat
  # Открываем доступ до веб интерфейса: Настройки программы (Ctrl+P) -> Дополнительно -> Веб интерфейс
  # Ставим галку "Использовать веб-интерфейс"
  # Придумываем логин и пароль (без спецсимволов или экранируем их), при желании ставим галку "Альтернативный порт" и указываем другой порт
  # Заполняем поля ниже
  username: admin
  password: admin
  port: 59876
  # Стратегия блокировки: 0 - блокируем все сторонние клиенты, 1 - при скачивании не блокирует тех кто отдаёт больше чем качает
  strategy: 0
  # Блокировка неактивных пиров, в секундах
  inactiveLimit: 120
  # Блокировать клиент: true - блокировать
  clearUTorrent: false
  clearBitTorrent: false
  clearLibTorrent: true
  # Не меняем
  url: http://127.0.0.1
